language: c
compiler:
  - gcc

env:
  - BTYPE="BINARY=64"
  - BTYPE="BINARY=64 USE_OPENMP=1"
  - BTYPE="BINARY=64 INTERFACE64=1"
  - BTYPE="BINARY=32"
  - BTYPE="BINARY=64 HOSTCC=gcc CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran"

before_install:
 - sudo apt-get install -qq gfortran gcc-mingw-w64-x86-64 gfortran-mingw-w64-x86-64 gcc-multilib gfortran-multilib

script: make QUIET_MAKE=1 DYNAMIC_ARCH=1 TARGET=NEHALEM NUM_THREADS=32 $BTYPE

# whitelist
branches:
  only:
    - master
    - develop