language: c
compiler:
  - gcc
script: make QUIET_MAKE=1 DYNAMIC_ARCH=1 TARGET=NEHALEM NUM_THREADS=32

before_install:
 - sudo apt-get install -qq gfortran

# whitelist
branches:
  only:
    - master
    - develop